DOCTORS = [

    {
        "id": 1,
        "name": "Dr. Aarav Mehta",
        "specialization": "General Physician",
        "experience": 12,
        "qualification": "MBBS, MD (Internal Medicine)",
        "rating": 4.8,
        "reviews": 1246,
        "hospital": "MediCare Prime Hospital",
        "address": "12 Health Avenue, Central District, New Delhi, Delhi 110001",
        "phone": "+91 90000 00001",
        "email": "aarav.mehta@example.com",
        "timings": "Mon-Sat, 10:00 AM - 2:00 PM",
        "languages": "English, Hindi",
        "consultation": "In-person, Video",
        "availability": "Available Today"
    },

    {
        "id": 2,
        "name": "Dr. Ananya Sharma",
        "specialization": "General Physician",
        "experience": 9,
        "qualification": "MBBS, MD (Medicine)",
        "rating": 4.7,
        "reviews": 982,
        "hospital": "WellLife Multispeciality Hospital",
        "address": "24 Wellness Road, Sector 18, Noida, Uttar Pradesh 201301",
        "phone": "+91 90000 00002",
        "email": "ananya.sharma@example.com",
        "timings": "Mon-Fri, 9:00 AM - 1:00 PM",
        "languages": "English, Hindi",
        "consultation": "In-person, Video",
        "availability": "Available Today"
    },

    {
        "id": 3,
        "name": "Dr. Rohan Kapoor",
        "specialization": "Cardiologist",
        "experience": 18,
        "qualification": "MBBS, MD, DM (Cardiology)",
        "rating": 4.9,
        "reviews": 2187,
        "hospital": "HeartCare Institute",
        "address": "45 Cardiac Lane, South Extension, New Delhi, Delhi 110049",
        "phone": "+91 90000 00003",
        "email": "rohan.kapoor@example.com",
        "timings": "Mon-Sat, 11:00 AM - 3:00 PM",
        "languages": "English, Hindi, Punjabi",
        "consultation": "In-person, Video",
        "availability": "Available Tomorrow"
    },

    {
        "id": 4,
        "name": "Dr. Priya Malhotra",
        "specialization": "Dermatologist",
        "experience": 11,
        "qualification": "MBBS, MD (Dermatology)",
        "rating": 4.8,
        "reviews": 1534,
        "hospital": "Skin & Wellness Centre",
        "address": "18 Wellness Street, Vasant Kunj, New Delhi, Delhi 110070",
        "phone": "+91 90000 00004",
        "email": "priya.malhotra@example.com",
        "timings": "Mon-Sat, 10:30 AM - 2:30 PM",
        "languages": "English, Hindi",
        "consultation": "In-person, Video",
        "availability": "Available Today"
    },

    {
        "id": 5,
        "name": "Dr. Kabir Verma",
        "specialization": "Orthopedic Surgeon",
        "experience": 16,
        "qualification": "MBBS, MS (Orthopedics)",
        "rating": 4.7,
        "reviews": 1368,
        "hospital": "OrthoCare Hospital",
        "address": "33 Joint Care Road, Sector 44, Gurugram, Haryana 122003",
        "phone": "+91 90000 00005",
        "email": "kabir.verma@example.com",
        "timings": "Mon-Fri, 4:00 PM - 8:00 PM",
        "languages": "English, Hindi",
        "consultation": "In-person",
        "availability": "Available Tomorrow"
    },

    {
        "id": 6,
        "name": "Dr. Meera Iyer",
        "specialization": "Gynecologist",
        "experience": 14,
        "qualification": "MBBS, MD (Obstetrics & Gynecology)",
        "rating": 4.9,
        "reviews": 1942,
        "hospital": "Women's Wellness Hospital",
        "address": "27 Harmony Avenue, Indiranagar, Bengaluru, Karnataka 560038",
        "phone": "+91 90000 00006",
        "email": "meera.iyer@example.com",
        "timings": "Mon-Sat, 9:30 AM - 1:30 PM",
        "languages": "English, Hindi, Kannada",
        "consultation": "In-person, Video",
        "availability": "Available Today"
    },

    {
        "id": 7,
        "name": "Dr. Aditya Rao",
        "specialization": "Neurologist",
        "experience": 20,
        "qualification": "MBBS, MD, DM (Neurology)",
        "rating": 4.8,
        "reviews": 1765,
        "hospital": "NeuroLife Institute",
        "address": "51 Brain Health Road, Banjara Hills, Hyderabad, Telangana 500034",
        "phone": "+91 90000 00007",
        "email": "aditya.rao@example.com",
        "timings": "Tue-Sat, 11:00 AM - 3:00 PM",
        "languages": "English, Hindi, Telugu",
        "consultation": "In-person, Video",
        "availability": "Available Tomorrow"
    },

    {
        "id": 8,
        "name": "Dr. Neha Bansal",
        "specialization": "Pediatrician",
        "experience": 10,
        "qualification": "MBBS, MD (Pediatrics)",
        "rating": 4.9,
        "reviews": 1621,
        "hospital": "LittleCare Children's Hospital",
        "address": "9 Rainbow Road, Sector 15, Chandigarh, Punjab 160015",
        "phone": "+91 90000 00008",
        "email": "neha.bansal@example.com",
        "timings": "Mon-Sat, 5:00 PM - 8:00 PM",
        "languages": "English, Hindi, Punjabi",
        "consultation": "In-person, Video",
        "availability": "Available Today"
    },

    {
        "id": 9,
        "name": "Dr. Vikram Joshi",
        "specialization": "Gastroenterologist",
        "experience": 15,
        "qualification": "MBBS, MD, DM (Gastroenterology)",
        "rating": 4.7,
        "reviews": 1189,
        "hospital": "Digestive Health Institute",
        "address": "14 Digestive Care Street, Pune, Maharashtra 411001",
        "phone": "+91 90000 00009",
        "email": "vikram.joshi@example.com",
        "timings": "Mon-Fri, 10:00 AM - 2:00 PM",
        "languages": "English, Hindi, Marathi",
        "consultation": "In-person, Video",
        "availability": "Available Tomorrow"
    },

    {
        "id": 10,
        "name": "Dr. Simran Kaur",
        "specialization": "Psychiatrist",
        "experience": 8,
        "qualification": "MBBS, MD (Psychiatry)",
        "rating": 4.8,
        "reviews": 934,
        "hospital": "MindWell Medical Centre",
        "address": "22 Peace Avenue, Sector 50, Gurugram, Haryana 122018",
        "phone": "+91 90000 00010",
        "email": "simran.kaur@example.com",
        "timings": "Mon-Sat, 3:00 PM - 7:00 PM",
        "languages": "English, Hindi, Punjabi",
        "consultation": "In-person, Video",
        "availability": "Available Today"
    },

    {
        "id": 11,
        "name": "Dr. Arjun Nair",
        "specialization": "Pulmonologist",
        "experience": 13,
        "qualification": "MBBS, MD, DM (Pulmonary Medicine)",
        "rating": 4.7,
        "reviews": 1087,
        "hospital": "RespiraCare Hospital",
        "address": "31 Breathing Avenue, Kochi, Kerala 682016",
        "phone": "+91 90000 00011",
        "email": "arjun.nair@example.com",
        "timings": "Mon-Sat, 10:00 AM - 1:00 PM",
        "languages": "English, Hindi, Malayalam",
        "consultation": "In-person, Video",
        "availability": "Available Tomorrow"
    },

    {
        "id": 12,
        "name": "Dr. Tanya Gupta",
        "specialization": "Endocrinologist",
        "experience": 12,
        "qualification": "MBBS, MD, DM (Endocrinology)",
        "rating": 4.8,
        "reviews": 1264,
        "hospital": "Metabolic Health Centre",
        "address": "16 Wellness Park, Jaipur, Rajasthan 302001",
        "phone": "+91 90000 00012",
        "email": "tanya.gupta@example.com",
        "timings": "Mon-Fri, 11:00 AM - 3:00 PM",
        "languages": "English, Hindi",
        "consultation": "In-person, Video",
        "availability": "Available Today"
    },

    {
        "id": 13,
        "name": "Dr. Rahul Menon",
        "specialization": "Nephrologist",
        "experience": 17,
        "qualification": "MBBS, MD, DM (Nephrology)",
        "rating": 4.9,
        "reviews": 1432,
        "hospital": "KidneyCare Institute",
        "address": "42 Renal Health Road, Chennai, Tamil Nadu 600018",
        "phone": "+91 90000 00013",
        "email": "rahul.menon@example.com",
        "timings": "Mon-Sat, 9:00 AM - 1:00 PM",
        "languages": "English, Hindi, Tamil",
        "consultation": "In-person, Video",
        "availability": "Available Tomorrow"
    },

    {
        "id": 14,
        "name": "Dr. Ishita Roy",
        "specialization": "Ophthalmologist",
        "experience": 9,
        "qualification": "MBBS, MS (Ophthalmology)",
        "rating": 4.7,
        "reviews": 876,
        "hospital": "ClearVision Eye Hospital",
        "address": "28 Vision Street, Kolkata, West Bengal 700020",
        "phone": "+91 90000 00014",
        "email": "ishita.roy@example.com",
        "timings": "Mon-Sat, 10:00 AM - 2:00 PM",
        "languages": "English, Hindi, Bengali",
        "consultation": "In-person",
        "availability": "Available Today"
    },

    {
        "id": 15,
        "name": "Dr. Manav Shah",
        "specialization": "ENT Specialist",
        "experience": 11,
        "qualification": "MBBS, MS (ENT)",
        "rating": 4.8,
        "reviews": 1032,
        "hospital": "Hear & Breathe Hospital",
        "address": "19 Wellness Boulevard, Ahmedabad, Gujarat 380009",
        "phone": "+91 90000 00015",
        "email": "manav.shah@example.com",
        "timings": "Mon-Fri, 4:00 PM - 7:00 PM",
        "languages": "English, Hindi, Gujarati",
        "consultation": "In-person, Video",
        "availability": "Available Today"
    },

    {
        "id": 16,
        "name": "Dr. Kavya Reddy",
        "specialization": "Gynecologist",
        "experience": 13,
        "qualification": "MBBS, MS (Obstetrics & Gynecology)",
        "rating": 4.9,
        "reviews": 1548,
        "hospital": "CareWomen Hospital",
        "address": "36 Harmony Road, Hyderabad, Telangana 500081",
        "phone": "+91 90000 00016",
        "email": "kavya.reddy@example.com",
        "timings": "Mon-Sat, 9:00 AM - 1:00 PM",
        "languages": "English, Hindi, Telugu",
        "consultation": "In-person, Video",
        "availability": "Available Tomorrow"
    },

    {
        "id": 17,
        "name": "Dr. Saurabh Jain",
        "specialization": "General Physician",
        "experience": 7,
        "qualification": "MBBS, MD (Internal Medicine)",
        "rating": 4.6,
        "reviews": 742,
        "hospital": "CityCare Medical Centre",
        "address": "8 Health Street, Lucknow, Uttar Pradesh 226001",
        "phone": "+91 90000 00017",
        "email": "saurabh.jain@example.com",
        "timings": "Mon-Sat, 8:00 AM - 12:00 PM",
        "languages": "English, Hindi",
        "consultation": "In-person, Video",
        "availability": "Available Today"
    },

    {
        "id": 18,
        "name": "Dr. Nandini Rao",
        "specialization": "Dermatologist",
        "experience": 10,
        "qualification": "MBBS, MD (Dermatology)",
        "rating": 4.8,
        "reviews": 1197,
        "hospital": "DermaCare Clinic",
        "address": "17 Skin Care Avenue, Bengaluru, Karnataka 560001",
        "phone": "+91 90000 00018",
        "email": "nandini.rao@example.com",
        "timings": "Tue-Sat, 11:00 AM - 4:00 PM",
        "languages": "English, Hindi, Kannada",
        "consultation": "In-person, Video",
        "availability": "Available Today"
    },

    {
        "id": 19,
        "name": "Dr. Dev Khanna",
        "specialization": "Cardiologist",
        "experience": 21,
        "qualification": "MBBS, MD, DM (Cardiology)",
        "rating": 4.9,
        "reviews": 2384,
        "hospital": "CardioLife Institute",
        "address": "63 Heart Avenue, Mumbai, Maharashtra 400001",
        "phone": "+91 90000 00019",
        "email": "dev.khanna@example.com",
        "timings": "Mon-Fri, 10:00 AM - 2:00 PM",
        "languages": "English, Hindi, Punjabi",
        "consultation": "In-person",
        "availability": "Available Tomorrow"
    },

    {
        "id": 20,
        "name": "Dr. Pooja Desai",
        "specialization": "Pediatrician",
        "experience": 12,
        "qualification": "MBBS, MD (Pediatrics)",
        "rating": 4.8,
        "reviews": 1357,
        "hospital": "HappyKids Hospital",
        "address": "25 Children's Avenue, Surat, Gujarat 395007",
        "phone": "+91 90000 00020",
        "email": "pooja.desai@example.com",
        "timings": "Mon-Sat, 5:00 PM - 8:00 PM",
        "languages": "English, Hindi, Gujarati",
        "consultation": "In-person, Video",
        "availability": "Available Today"
    },

    {
        "id": 21,
        "name": "Dr. Yash Malhotra",
        "specialization": "Orthopedic Surgeon",
        "experience": 14,
        "qualification": "MBBS, MS (Orthopedics)",
        "rating": 4.7,
        "reviews": 1098,
        "hospital": "Bone & Joint Care Hospital",
        "address": "44 Mobility Road, Indore, Madhya Pradesh 452001",
        "phone": "+91 90000 00021",
        "email": "yash.malhotra@example.com",
        "timings": "Mon-Sat, 4:00 PM - 8:00 PM",
        "languages": "English, Hindi",
        "consultation": "In-person",
        "availability": "Available Tomorrow"
    },

    {
        "id": 22,
        "name": "Dr. Riya Mukherjee",
        "specialization": "Neurologist",
        "experience": 16,
        "qualification": "MBBS, MD, DM (Neurology)",
        "rating": 4.8,
        "reviews": 1287,
        "hospital": "NeuroCare Medical Centre",
        "address": "11 Brain Health Avenue, Kolkata, West Bengal 700091",
        "phone": "+91 90000 00022",
        "email": "riya.mukherjee@example.com",
        "timings": "Mon-Fri, 2:00 PM - 6:00 PM",
        "languages": "English, Hindi, Bengali",
        "consultation": "In-person, Video",
        "availability": "Available Today"
    },

    {
        "id": 23,
        "name": "Dr. Karan Bhatia",
        "specialization": "Gastroenterologist",
        "experience": 13,
        "qualification": "MBBS, MD, DM (Gastroenterology)",
        "rating": 4.7,
        "reviews": 945,
        "hospital": "DigestiveCare Hospital",
        "address": "29 Gut Health Road, New Delhi, Delhi 110025",
        "phone": "+91 90000 00023",
        "email": "karan.bhatia@example.com",
        "timings": "Mon-Sat, 9:00 AM - 1:00 PM",
        "languages": "English, Hindi",
        "consultation": "In-person, Video",
        "availability": "Available Tomorrow"
    },

    {
        "id": 24,
        "name": "Dr. Aditi Kulkarni",
        "specialization": "Endocrinologist",
        "experience": 11,
        "qualification": "MBBS, MD, DM (Endocrinology)",
        "rating": 4.8,
        "reviews": 1124,
        "hospital": "HormoneCare Institute",
        "address": "52 Metabolic Avenue, Pune, Maharashtra 411014",
        "phone": "+91 90000 00024",
        "email": "aditi.kulkarni@example.com",
        "timings": "Mon-Fri, 10:00 AM - 2:00 PM",
        "languages": "English, Hindi, Marathi",
        "consultation": "In-person, Video",
        "availability": "Available Today"
    },

    {
        "id": 25,
        "name": "Dr. Sameer Thomas",
        "specialization": "Pulmonologist",
        "experience": 15,
        "qualification": "MBBS, MD (Pulmonary Medicine)",
        "rating": 4.7,
        "reviews": 1038,
        "hospital": "LungCare Hospital",
        "address": "38 Respiratory Road, Chennai, Tamil Nadu 600040",
        "phone": "+91 90000 00025",
        "email": "sameer.thomas@example.com",
        "timings": "Mon-Sat, 11:00 AM - 3:00 PM",
        "languages": "English, Hindi, Tamil",
        "consultation": "In-person, Video",
        "availability": "Available Tomorrow"
    },

    {
        "id": 26,
        "name": "Dr. Sneha Kapoor",
        "specialization": "Psychiatrist",
        "experience": 9,
        "qualification": "MBBS, MD (Psychiatry)",
        "rating": 4.8,
        "reviews": 867,
        "hospital": "MindCare Hospital",
        "address": "7 Mental Wellness Road, Chandigarh, Punjab 160017",
        "phone": "+91 90000 00026",
        "email": "sneha.kapoor@example.com",
        "timings": "Mon-Sat, 4:00 PM - 8:00 PM",
        "languages": "English, Hindi, Punjabi",
        "consultation": "In-person, Video",
        "availability": "Available Today"
    },

    {
        "id": 27,
        "name": "Dr. Harsh Vardhan",
        "specialization": "Nephrologist",
        "experience": 19,
        "qualification": "MBBS, MD, DM (Nephrology)",
        "rating": 4.9,
        "reviews": 1764,
        "hospital": "RenalCare Institute",
        "address": "61 Kidney Health Road, Bengaluru, Karnataka 560076",
        "phone": "+91 90000 00027",
        "email": "harsh.vardhan@example.com",
        "timings": "Mon-Fri, 9:30 AM - 1:30 PM",
        "languages": "English, Hindi, Kannada",
        "consultation": "In-person, Video",
        "availability": "Available Tomorrow"
    },

    {
        "id": 28,
        "name": "Dr. Ishaan Sethi",
        "specialization": "Ophthalmologist",
        "experience": 10,
        "qualification": "MBBS, MS (Ophthalmology)",
        "rating": 4.7,
        "reviews": 921,
        "hospital": "VisionPlus Eye Centre",
        "address": "15 Vision Avenue, Jaipur, Rajasthan 302017",
        "phone": "+91 90000 00028",
        "email": "ishaan.sethi@example.com",
        "timings": "Mon-Sat, 9:00 AM - 1:00 PM",
        "languages": "English, Hindi",
        "consultation": "In-person",
        "availability": "Available Today"
    },

    {
        "id": 29,
        "name": "Dr. Monica Fernandes",
        "specialization": "ENT Specialist",
        "experience": 14,
        "qualification": "MBBS, MS (ENT)",
        "rating": 4.8,
        "reviews": 1163,
        "hospital": "ENT & Hearing Institute",
        "address": "26 Hearing Road, Mumbai, Maharashtra 400050",
        "phone": "+91 90000 00029",
        "email": "monica.fernandes@example.com",
        "timings": "Mon-Fri, 3:00 PM - 7:00 PM",
        "languages": "English, Hindi, Marathi",
        "consultation": "In-person, Video",
        "availability": "Available Tomorrow"
    },

    {
        "id": 30,
        "name": "Dr. Nikhil Agarwal",
        "specialization": "General Physician",
        "experience": 6,
        "qualification": "MBBS, MD (Medicine)",
        "rating": 4.6,
        "reviews": 634,
        "hospital": "PrimeHealth Clinic",
        "address": "10 Health Park, Gurugram, Haryana 122009",
        "phone": "+91 90000 00030",
        "email": "nikhil.agarwal@example.com",
        "timings": "Mon-Sat, 8:30 AM - 12:30 PM",
        "languages": "English, Hindi",
        "consultation": "In-person, Video",
        "availability": "Available Today"
    },

    {
        "id": 31,
        "name": "Dr. Shreya Nanda",
        "specialization": "Cardiologist",
        "experience": 13,
        "qualification": "MBBS, MD, DM (Cardiology)",
        "rating": 4.8,
        "reviews": 1326,
        "hospital": "HeartFirst Hospital",
        "address": "73 Cardiac Avenue, Noida, Uttar Pradesh 201304",
        "phone": "+91 90000 00031",
        "email": "shreya.nanda@example.com",
        "timings": "Tue-Sat, 10:00 AM - 2:00 PM",
        "languages": "English, Hindi",
        "consultation": "In-person, Video",
        "availability": "Available Tomorrow"
    },

    {
        "id": 32,
        "name": "Dr. Raghav Singh",
        "specialization": "Orthopedic Surgeon",
        "experience": 18,
        "qualification": "MBBS, MS (Orthopedics)",
        "rating": 4.9,
        "reviews": 1876,
        "hospital": "MobilityCare Hospital",
        "address": "48 Bone & Joint Road, Lucknow, Uttar Pradesh 226010",
        "phone": "+91 90000 00032",
        "email": "raghav.singh@example.com",
        "timings": "Mon-Fri, 5:00 PM - 8:00 PM",
        "languages": "English, Hindi",
        "consultation": "In-person",
        "availability": "Available Today"
    },

    {
        "id": 33,
        "name": "Dr. Diya Menon",
        "specialization": "Dermatologist",
        "experience": 8,
        "qualification": "MBBS, MD (Dermatology)",
        "rating": 4.7,
        "reviews": 781,
        "hospital": "GlowSkin Medical Centre",
        "address": "21 Skin Wellness Road, Kochi, Kerala 682018",
        "phone": "+91 90000 00033",
        "email": "diya.menon@example.com",
        "timings": "Mon-Sat, 11:00 AM - 3:00 PM",
        "languages": "English, Hindi, Malayalam",
        "consultation": "In-person, Video",
        "availability": "Available Today"
    },

    {
        "id": 34,
        "name": "Dr. Varun Chawla",
        "specialization": "Neurologist",
        "experience": 17,
        "qualification": "MBBS, MD, DM (Neurology)",
        "rating": 4.8,
        "reviews": 1498,
        "hospital": "BrainCare Institute",
        "address": "39 Neuro Avenue, New Delhi, Delhi 110016",
        "phone": "+91 90000 00034",
        "email": "varun.chawla@example.com",
        "timings": "Mon-Fri, 12:00 PM - 4:00 PM",
        "languages": "English, Hindi",
        "consultation": "In-person, Video",
        "availability": "Available Tomorrow"
    },

    {
        "id": 35,
        "name": "Dr. Alisha Thomas",
        "specialization": "Pediatrician",
        "experience": 9,
        "qualification": "MBBS, MD (Pediatrics)",
        "rating": 4.9,
        "reviews": 1107,
        "hospital": "ChildCare Plus Hospital",
        "address": "12 Children's Wellness Road, Bengaluru, Karnataka 560103",
        "phone": "+91 90000 00035",
        "email": "alisha.thomas@example.com",
        "timings": "Mon-Sat, 4:00 PM - 7:00 PM",
        "languages": "English, Hindi, Kannada",
        "consultation": "In-person, Video",
        "availability": "Available Today"
    },

    {
        "id": 36,
        "name": "Dr. Mohit Bedi",
        "specialization": "Gastroenterologist",
        "experience": 14,
        "qualification": "MBBS, MD, DM (Gastroenterology)",
        "rating": 4.8,
        "reviews": 1218,
        "hospital": "GutHealth Institute",
        "address": "56 Digestive Health Road, Mumbai, Maharashtra 400070",
        "phone": "+91 90000 00036",
        "email": "mohit.bedi@example.com",
        "timings": "Mon-Sat, 10:00 AM - 2:00 PM",
        "languages": "English, Hindi, Marathi",
        "consultation": "In-person, Video",
        "availability": "Available Tomorrow"
    },

    {
        "id": 37,
        "name": "Dr. Ritu Saxena",
        "specialization": "Endocrinologist",
        "experience": 15,
        "qualification": "MBBS, MD, DM (Endocrinology)",
        "rating": 4.9,
        "reviews": 1389,
        "hospital": "EndoCare Medical Institute",
        "address": "34 Diabetes Care Avenue, Delhi 110017",
        "phone": "+91 90000 00037",
        "email": "ritu.saxena@example.com",
        "timings": "Mon-Fri, 9:00 AM - 1:00 PM",
        "languages": "English, Hindi",
        "consultation": "In-person, Video",
        "availability": "Available Today"
    },

    {
        "id": 38,
        "name": "Dr. Kunal Deshmukh",
        "specialization": "Pulmonologist",
        "experience": 12,
        "qualification": "MBBS, MD (Pulmonary Medicine)",
        "rating": 4.7,
        "reviews": 914,
        "hospital": "BreathEasy Hospital",
        "address": "47 Respiratory Avenue, Pune, Maharashtra 411038",
        "phone": "+91 90000 00038",
        "email": "kunal.deshmukh@example.com",
        "timings": "Mon-Sat, 10:00 AM - 1:00 PM",
        "languages": "English, Hindi, Marathi",
        "consultation": "In-person, Video",
        "availability": "Available Tomorrow"
    },

    {
        "id": 39,
        "name": "Dr. Anjali Verma",
        "specialization": "Psychiatrist",
        "experience": 11,
        "qualification": "MBBS, MD (Psychiatry)",
        "rating": 4.8,
        "reviews": 1056,
        "hospital": "Mental Wellness Institute",
        "address": "23 MindCare Avenue, Jaipur, Rajasthan 302018",
        "phone": "+91 90000 00039",
        "email": "anjali.verma@example.com",
        "timings": "Mon-Sat, 2:00 PM - 6:00 PM",
        "languages": "English, Hindi",
        "consultation": "In-person, Video",
        "availability": "Available Today"
    },

    {
        "id": 40,
        "name": "Dr. Arvind Pillai",
        "specialization": "Nephrologist",
        "experience": 18,
        "qualification": "MBBS, MD, DM (Nephrology)",
        "rating": 4.9,
        "reviews": 1567,
        "hospital": "Kidney Wellness Institute",
        "address": "64 Renal Care Road, Chennai, Tamil Nadu 600028",
        "phone": "+91 90000 00040",
        "email": "arvind.pillai@example.com",
        "timings": "Mon-Fri, 9:00 AM - 1:00 PM",
        "languages": "English, Hindi, Tamil",
        "consultation": "In-person, Video",
        "availability": "Available Tomorrow"
    },

    {
        "id": 41,
        "name": "Dr. Reema Arora",
        "specialization": "Ophthalmologist",
        "experience": 12,
        "qualification": "MBBS, MS (Ophthalmology)",
        "rating": 4.8,
        "reviews": 987,
        "hospital": "EyeCare Vision Hospital",
        "address": "18 Vision Park, Chandigarh, Punjab 160036",
        "phone": "+91 90000 00041",
        "email": "reema.arora@example.com",
        "timings": "Mon-Sat, 10:00 AM - 2:00 PM",
        "languages": "English, Hindi, Punjabi",
        "consultation": "In-person",
        "availability": "Available Today"
    },

    {
        "id": 42,
        "name": "Dr. Sameera Khan",
        "specialization": "ENT Specialist",
        "experience": 10,
        "qualification": "MBBS, MS (ENT)",
        "rating": 4.7,
        "reviews": 823,
        "hospital": "ENTCare Hospital",
        "address": "32 Hearing Avenue, Hyderabad, Telangana 500082",
        "phone": "+91 90000 00042",
        "email": "sameera.khan@example.com",
        "timings": "Mon-Fri, 3:00 PM - 7:00 PM",
        "languages": "English, Hindi, Telugu",
        "consultation": "In-person, Video",
        "availability": "Available Tomorrow"
    },

    {
        "id": 43,
        "name": "Dr. Rohit Sinha",
        "specialization": "General Physician",
        "experience": 10,
        "qualification": "MBBS, MD (Internal Medicine)",
        "rating": 4.7,
        "reviews": 903,
        "hospital": "MediFirst Hospital",
        "address": "41 Health Avenue, Patna, Bihar 800001",
        "phone": "+91 90000 00043",
        "email": "rohit.sinha@example.com",
        "timings": "Mon-Sat, 9:00 AM - 1:00 PM",
        "languages": "English, Hindi",
        "consultation": "In-person, Video",
        "availability": "Available Today"
    },

    {
        "id": 44,
        "name": "Dr. Nisha Patel",
        "specialization": "Gynecologist",
        "experience": 15,
        "qualification": "MBBS, MD (Obstetrics & Gynecology)",
        "rating": 4.9,
        "reviews": 1742,
        "hospital": "Women's Care Institute",
        "address": "29 Women's Health Road, Ahmedabad, Gujarat 380015",
        "phone": "+91 90000 00044",
        "email": "nisha.patel@example.com",
        "timings": "Mon-Sat, 10:00 AM - 2:00 PM",
        "languages": "English, Hindi, Gujarati",
        "consultation": "In-person, Video",
        "availability": "Available Tomorrow"
    },

    {
        "id": 45,
        "name": "Dr. Siddharth Bose",
        "specialization": "Cardiologist",
        "experience": 19,
        "qualification": "MBBS, MD, DM (Cardiology)",
        "rating": 4.8,
        "reviews": 1618,
        "hospital": "HeartWell Medical Institute",
        "address": "58 Cardiac Care Road, Kolkata, West Bengal 700029",
        "phone": "+91 90000 00045",
        "email": "siddharth.bose@example.com",
        "timings": "Tue-Sat, 11:00 AM - 3:00 PM",
        "languages": "English, Hindi, Bengali",
        "consultation": "In-person, Video",
        "availability": "Available Today"
    },

    {
        "id": 46,
        "name": "Dr. Aakash Tiwari",
        "specialization": "Orthopedic Surgeon",
        "experience": 11,
        "qualification": "MBBS, MS (Orthopedics)",
        "rating": 4.7,
        "reviews": 968,
        "hospital": "OrthoLife Hospital",
        "address": "35 Mobility Avenue, Bhopal, Madhya Pradesh 462001",
        "phone": "+91 90000 00046",
        "email": "aakash.tiwari@example.com",
        "timings": "Mon-Fri, 4:00 PM - 8:00 PM",
        "languages": "English, Hindi",
        "consultation": "In-person",
        "availability": "Available Tomorrow"
    },

    {
        "id": 47,
        "name": "Dr. Tara Srinivas",
        "specialization": "Dermatologist",
        "experience": 13,
        "qualification": "MBBS, MD (Dermatology)",
        "rating": 4.9,
        "reviews": 1456,
        "hospital": "SkinHealth Institute",
        "address": "46 Dermatology Road, Chennai, Tamil Nadu 600034",
        "phone": "+91 90000 00047",
        "email": "tara.srinivas@example.com",
        "timings": "Mon-Sat, 11:00 AM - 3:00 PM",
        "languages": "English, Hindi, Tamil",
        "consultation": "In-person, Video",
        "availability": "Available Today"
    },

    {
        "id": 48,
        "name": "Dr. Manish Goyal",
        "specialization": "Neurologist",
        "experience": 14,
        "qualification": "MBBS, MD, DM (Neurology)",
        "rating": 4.8,
        "reviews": 1178,
        "hospital": "NeuroHealth Hospital",
        "address": "53 Neurology Avenue, Indore, Madhya Pradesh 452010",
        "phone": "+91 90000 00048",
        "email": "manish.goyal@example.com",
        "timings": "Mon-Fri, 1:00 PM - 5:00 PM",
        "languages": "English, Hindi",
        "consultation": "In-person, Video",
        "availability": "Available Tomorrow"
    },

    {
        "id": 49,
        "name": "Dr. Farah Ali",
        "specialization": "Pediatrician",
        "experience": 10,
        "qualification": "MBBS, MD (Pediatrics)",
        "rating": 4.9,
        "reviews": 1284,
        "hospital": "KidsFirst Medical Centre",
        "address": "20 Child Wellness Road, Lucknow, Uttar Pradesh 226016",
        "phone": "+91 90000 00049",
        "email": "farah.ali@example.com",
        "timings": "Mon-Sat, 5:00 PM - 8:00 PM",
        "languages": "English, Hindi",
        "consultation": "In-person, Video",
        "availability": "Available Today"
    },

    {
        "id": 50,
        "name": "Dr. Vivek Narang",
        "specialization": "General Physician",
        "experience": 22,
        "qualification": "MBBS, MD (Internal Medicine)",
        "rating": 4.9,
        "reviews": 2457,
        "hospital": "MediGuide Advanced Hospital",
        "address": "72 Medical Avenue, South Delhi, Delhi 110025",
        "phone": "+91 90000 00050",
        "email": "vivek.narang@example.com",
        "timings": "Mon-Sat, 9:00 AM - 1:00 PM",
        "languages": "English, Hindi, Punjabi",
        "consultation": "In-person, Video",
        "availability": "Available Today"
    }

]